os: linux
dist: xenial
language: python
python:
- 3.8.10
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c "CREATE DATABASE flo_expense_tracker_test_db;" -U postgres
- psql -c "CREATE USER kiarie WITH PASSWORD '7194';" -U postgres
env:
  matrix:
  - TEST_DATABASE_URL="postgres://kiarie:7194@localhost/flo_expense_tracker_test_db"
  # global:
  # - secure: 
script:
- python -m pytest --cov=app/api
after_success:
- coveralls
- bash <(curl -s https://codecov.io/bash)
