"""initializing the database

Revision ID: 3ff850dc826f
Revises: 
Create Date: 2022-06-21 13:35:15.995989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff850dc826f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Expense',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expense_sys_id', sa.String(length=25), nullable=False),
    sa.Column('expense_for', sa.String(length=25), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('expense_client', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_sys_id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_sys_id', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_sys_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('Expense')
    # ### end Alembic commands ###
